### ISSUE TITLE
Mismatch between the code and the paper

### ISSUE THREAD

**Issue by xingyi-li** [Xuanmeng-Zhang/MVCGAN#2]
Hi @Xuanmeng-Zhang, thanks for your excellent work. Unfortunately, in my opinion, the code you release is a little bit different from your description in the paper. 

Specifically, I don't think that there are so-called two stages because:
1. I did not find the feature-level projection loss (described in eq. (8)) in the code. 
2. Also, images created by volume rendering are only used to calculate image-level projection loss. In contrast, the gen_imgs are always produced by first performing feature-level stereo mixup and then processing by the decoder. This contradicts with "stage I" because in "stage I", images should be volumetrically rendered rather than using a decoder, as illustrated in Fig 4.

Could you kindly explain? 
Thanks!

**Comment by Xuanmeng-Zhang** [comment]
Hi @xingyi-li, you are right. The reasons are as follows.
1. We find that applying image-level loss on low-resolution images (64^2) has the same effect as directly feature-level loss, because the geometry constraint is still applied on the feature via gradient back-propagation.
2. We find that both perform image rendering and feature rendering can work well in "stage I", because the image rendering can be approximated with “early aggregation” with decoder  (refer to [StyleNerf](https://openreview.net/forum?id=iUuzzTMUw9K) ). 
3. To make the framework neater, we instead provide a unified implementation for both "stage 1" and "stage 2".

**Comment by xingyi-li** [comment]
OK, that explains it. Thanks!

**Comment by AlbertHuyb** [comment]
@Xuanmeng-Zhang I'm also confused about this specific implementation. 

1. I noticed that the reprojection loss is placed on theRGB output of the siren network `G_s`. However, such RGB output of `G_s` is totally not optimized and not utilized by the following modules. I wonder how such reprojection loss works in the proposed multi-view consistency framework.

2. On the other hand, the mix-up module doesn't pay much attention on the `warp_aux_feat_map`. The `mix_up_ratio` of `warp_aux_feat_map` is randomly generated and is up to only 0.3, which means that the mixed feature map pays much more attention to the primary feature map.

Could you please explain these two points? 

Thanks.
